### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by MonadicT** [tomkp/react-layout-pane#2]
HI,

I get the error mentioned above. The call stack is below. I also have a small example for reproducing the error at  https://github.com/MonadicT/rlpbug. 

Thanks for any pointers as to where the problem is.

Uncaught TypeError: Cannot call a class as a function_classCallCheck @ Layout.js:13Layout @ Layout.js:27ReactLegacyElementFactory.wrapCreateElement.legacyCreateElement @ ReactLegacyElement.js:192render @ clientapp.js:47(anonymous function) @ ReactCompositeComponent.js:1261ReactPerf.measure.wrapper @ ReactPerf.js:51(anonymous function) @ ReactCompositeComponent.js:803ReactPerf.measure.wrapper @ ReactPerf.js:51ReactComponent.Mixin._mountComponentIntoNode @ ReactComponent.js:406Mixin.perform @ Transaction.js:135ReactComponent.Mixin.mountComponentIntoNode @ ReactComponent.js:382(anonymous function) @ ReactMount.js:313ReactPerf.measure.wrapper @ ReactPerf.js:51ReactMount.render @ ReactMount.js:382ReactPerf.measure.wrapper @ ReactPerf.js:511../components/clientapp @ app.js:10s @ _prelude.js:1e @ _prelude.js:1(anonymous function) @ _prelude.js:1

**Comment by tomkp** [comment]
I'm unable to reproduce this - I'll keep digging but have you been able to fix it?

**Comment by MonadicT** [comment]
Hi Tom,

I should have replied sooner. I was unable to root cause it and I just
started over with a new project and I have not seen this error since. My
guest is that somehow  I ended up with incompatible set of npm modules.

Thanks for looking into the problem. Please close the issue as you see fit.

Praki
